### ISSUE TITLE
Highscores Fetcher

### ISSUE THREAD

**Issue by renatorib** [TibiaJS/tibia-crawler#8]
Highscores fetcher, passing `world`,  `page` _(0 as default)_ and `list` _(experience as default)_, and returning different arrays according to `list`.
## Path

Page 1 from Antica's shielding highscores
`?subtopic=highscores&world=Antica&list=shielding&page=1`
## Lists and return indexes

**`experience`**
`rank` `name` `level` `points`

**`achievements`**
`rank` `name` `points`

**`loyalty`**
`rank` `name` `title` `points`

**`magic` `shielding` `distance` `axe` `sword` `club` `fist` `fishing`**
`rank` `name` `level`

**Comment by gpedro** [comment]
:+1:
